disallowed-names = [
  "..",
  "e", # no single letter error bindings
]
disallowed-methods = [
  { path = "std::cell::RefCell::default()", reason = "prefer explicit inner type default" },
  { path = "std::rc::Rc::default()", reason = "prefer explicit inner type default" },
]
