exclude = ["target/*"]
include = ["**/*.toml"]

[formatting]
column_width = 100
align_comments = false

[[rule]]
include = ["**/Cargo.toml"]
keys = ["features"]
formatting.column_width = 105
formatting.reorder_keys = false

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies",
  "*-dependencies",
  "workspace.dependencies",
  "workspace.*-dependencies",
  "target.*.dependencies",
  "target.*.*-dependencies",
]
formatting.column_width = 120
formatting.reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "dependencies.*",
  "*-dependencies.*",
  "workspace.dependencies.*",
  "workspace.*-dependencies.*",
  "target.*.dependencies",
  "target.*.*-dependencies",
]
formatting.column_width = 120
formatting.reorder_keys = false
